// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/v1/cel-service.proto

package cel_service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import checked "github.com/google/cel-spec/proto/checked/v1/checked"
import eval "github.com/google/cel-spec/proto/v1/eval"
import syntax "github.com/google/cel-spec/proto/v1/syntax"
import rpc "github.com/googleapis/googleapis/google/rpc"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusDetails_Severity int32

const (
	StatusDetails_SEVERITY_UNSPECIFIED StatusDetails_Severity = 0
	StatusDetails_DEPRECATION          StatusDetails_Severity = 1
	StatusDetails_WARNING              StatusDetails_Severity = 2
	StatusDetails_ERROR                StatusDetails_Severity = 3
)

var StatusDetails_Severity_name = map[int32]string{
	0: "SEVERITY_UNSPECIFIED",
	1: "DEPRECATION",
	2: "WARNING",
	3: "ERROR",
}
var StatusDetails_Severity_value = map[string]int32{
	"SEVERITY_UNSPECIFIED": 0,
	"DEPRECATION":          1,
	"WARNING":              2,
	"ERROR":                3,
}

func (x StatusDetails_Severity) String() string {
	return proto.EnumName(StatusDetails_Severity_name, int32(x))
}
func (StatusDetails_Severity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cel_service_42f011481c95485e, []int{0, 0}
}

type StatusDetails struct {
	Severity             StatusDetails_Severity `protobuf:"varint,1,opt,name=severity,enum=google.api.expr.v1.StatusDetails_Severity" json:"severity,omitempty"`
	Line                 int32                  `protobuf:"varint,2,opt,name=line" json:"line,omitempty"`
	Column               int32                  `protobuf:"varint,3,opt,name=column" json:"column,omitempty"`
	Id                   int64                  `protobuf:"varint,4,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StatusDetails) Reset()         { *m = StatusDetails{} }
func (m *StatusDetails) String() string { return proto.CompactTextString(m) }
func (*StatusDetails) ProtoMessage()    {}
func (*StatusDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_cel_service_42f011481c95485e, []int{0}
}
func (m *StatusDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusDetails.Unmarshal(m, b)
}
func (m *StatusDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusDetails.Marshal(b, m, deterministic)
}
func (dst *StatusDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusDetails.Merge(dst, src)
}
func (m *StatusDetails) XXX_Size() int {
	return xxx_messageInfo_StatusDetails.Size(m)
}
func (m *StatusDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusDetails.DiscardUnknown(m)
}

var xxx_messageInfo_StatusDetails proto.InternalMessageInfo

func (m *StatusDetails) GetSeverity() StatusDetails_Severity {
	if m != nil {
		return m.Severity
	}
	return StatusDetails_SEVERITY_UNSPECIFIED
}

func (m *StatusDetails) GetLine() int32 {
	if m != nil {
		return m.Line
	}
	return 0
}

func (m *StatusDetails) GetColumn() int32 {
	if m != nil {
		return m.Column
	}
	return 0
}

func (m *StatusDetails) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ParseRequest struct {
	CelSource            string   `protobuf:"bytes,1,opt,name=cel_source,json=celSource" json:"cel_source,omitempty"`
	SyntaxVersion        string   `protobuf:"bytes,2,opt,name=syntax_version,json=syntaxVersion" json:"syntax_version,omitempty"`
	SourceLocation       string   `protobuf:"bytes,3,opt,name=source_location,json=sourceLocation" json:"source_location,omitempty"`
	DisableMacros        bool     `protobuf:"varint,4,opt,name=disable_macros,json=disableMacros" json:"disable_macros,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParseRequest) Reset()         { *m = ParseRequest{} }
func (m *ParseRequest) String() string { return proto.CompactTextString(m) }
func (*ParseRequest) ProtoMessage()    {}
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cel_service_42f011481c95485e, []int{1}
}
func (m *ParseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseRequest.Unmarshal(m, b)
}
func (m *ParseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseRequest.Marshal(b, m, deterministic)
}
func (dst *ParseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseRequest.Merge(dst, src)
}
func (m *ParseRequest) XXX_Size() int {
	return xxx_messageInfo_ParseRequest.Size(m)
}
func (m *ParseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ParseRequest proto.InternalMessageInfo

func (m *ParseRequest) GetCelSource() string {
	if m != nil {
		return m.CelSource
	}
	return ""
}

func (m *ParseRequest) GetSyntaxVersion() string {
	if m != nil {
		return m.SyntaxVersion
	}
	return ""
}

func (m *ParseRequest) GetSourceLocation() string {
	if m != nil {
		return m.SourceLocation
	}
	return ""
}

func (m *ParseRequest) GetDisableMacros() bool {
	if m != nil {
		return m.DisableMacros
	}
	return false
}

type ParseResponse struct {
	ParsedExpr           *syntax.ParsedExpr `protobuf:"bytes,1,opt,name=parsed_expr,json=parsedExpr" json:"parsed_expr,omitempty"`
	Issues               []*rpc.Status      `protobuf:"bytes,2,rep,name=issues" json:"issues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ParseResponse) Reset()         { *m = ParseResponse{} }
func (m *ParseResponse) String() string { return proto.CompactTextString(m) }
func (*ParseResponse) ProtoMessage()    {}
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cel_service_42f011481c95485e, []int{2}
}
func (m *ParseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseResponse.Unmarshal(m, b)
}
func (m *ParseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseResponse.Marshal(b, m, deterministic)
}
func (dst *ParseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseResponse.Merge(dst, src)
}
func (m *ParseResponse) XXX_Size() int {
	return xxx_messageInfo_ParseResponse.Size(m)
}
func (m *ParseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ParseResponse proto.InternalMessageInfo

func (m *ParseResponse) GetParsedExpr() *syntax.ParsedExpr {
	if m != nil {
		return m.ParsedExpr
	}
	return nil
}

func (m *ParseResponse) GetIssues() []*rpc.Status {
	if m != nil {
		return m.Issues
	}
	return nil
}

type CheckRequest struct {
	ParsedExpr           *syntax.ParsedExpr `protobuf:"bytes,1,opt,name=parsed_expr,json=parsedExpr" json:"parsed_expr,omitempty"`
	TypeEnv              []*checked.Decl    `protobuf:"bytes,2,rep,name=type_env,json=typeEnv" json:"type_env,omitempty"`
	Container            string             `protobuf:"bytes,3,opt,name=container" json:"container,omitempty"`
	NoStdEnv             bool               `protobuf:"varint,4,opt,name=no_std_env,json=noStdEnv" json:"no_std_env,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CheckRequest) Reset()         { *m = CheckRequest{} }
func (m *CheckRequest) String() string { return proto.CompactTextString(m) }
func (*CheckRequest) ProtoMessage()    {}
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cel_service_42f011481c95485e, []int{3}
}
func (m *CheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckRequest.Unmarshal(m, b)
}
func (m *CheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckRequest.Marshal(b, m, deterministic)
}
func (dst *CheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckRequest.Merge(dst, src)
}
func (m *CheckRequest) XXX_Size() int {
	return xxx_messageInfo_CheckRequest.Size(m)
}
func (m *CheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckRequest proto.InternalMessageInfo

func (m *CheckRequest) GetParsedExpr() *syntax.ParsedExpr {
	if m != nil {
		return m.ParsedExpr
	}
	return nil
}

func (m *CheckRequest) GetTypeEnv() []*checked.Decl {
	if m != nil {
		return m.TypeEnv
	}
	return nil
}

func (m *CheckRequest) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

func (m *CheckRequest) GetNoStdEnv() bool {
	if m != nil {
		return m.NoStdEnv
	}
	return false
}

type CheckResponse struct {
	CheckedExpr          *checked.CheckedExpr `protobuf:"bytes,1,opt,name=checked_expr,json=checkedExpr" json:"checked_expr,omitempty"`
	Issues               []*rpc.Status        `protobuf:"bytes,2,rep,name=issues" json:"issues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CheckResponse) Reset()         { *m = CheckResponse{} }
func (m *CheckResponse) String() string { return proto.CompactTextString(m) }
func (*CheckResponse) ProtoMessage()    {}
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cel_service_42f011481c95485e, []int{4}
}
func (m *CheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckResponse.Unmarshal(m, b)
}
func (m *CheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckResponse.Marshal(b, m, deterministic)
}
func (dst *CheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckResponse.Merge(dst, src)
}
func (m *CheckResponse) XXX_Size() int {
	return xxx_messageInfo_CheckResponse.Size(m)
}
func (m *CheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckResponse proto.InternalMessageInfo

func (m *CheckResponse) GetCheckedExpr() *checked.CheckedExpr {
	if m != nil {
		return m.CheckedExpr
	}
	return nil
}

func (m *CheckResponse) GetIssues() []*rpc.Status {
	if m != nil {
		return m.Issues
	}
	return nil
}

type EvalRequest struct {
	// Types that are valid to be assigned to ExprKind:
	//	*EvalRequest_ParsedExpr
	//	*EvalRequest_CheckedExpr
	ExprKind             isEvalRequest_ExprKind     `protobuf_oneof:"expr_kind"`
	Bindings             map[string]*eval.ExprValue `protobuf:"bytes,3,rep,name=bindings" json:"bindings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Container            string                     `protobuf:"bytes,4,opt,name=container" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *EvalRequest) Reset()         { *m = EvalRequest{} }
func (m *EvalRequest) String() string { return proto.CompactTextString(m) }
func (*EvalRequest) ProtoMessage()    {}
func (*EvalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cel_service_42f011481c95485e, []int{5}
}
func (m *EvalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvalRequest.Unmarshal(m, b)
}
func (m *EvalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvalRequest.Marshal(b, m, deterministic)
}
func (dst *EvalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvalRequest.Merge(dst, src)
}
func (m *EvalRequest) XXX_Size() int {
	return xxx_messageInfo_EvalRequest.Size(m)
}
func (m *EvalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EvalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EvalRequest proto.InternalMessageInfo

type isEvalRequest_ExprKind interface {
	isEvalRequest_ExprKind()
}

type EvalRequest_ParsedExpr struct {
	ParsedExpr *syntax.ParsedExpr `protobuf:"bytes,1,opt,name=parsed_expr,json=parsedExpr,oneof"`
}
type EvalRequest_CheckedExpr struct {
	CheckedExpr *checked.CheckedExpr `protobuf:"bytes,2,opt,name=checked_expr,json=checkedExpr,oneof"`
}

func (*EvalRequest_ParsedExpr) isEvalRequest_ExprKind()  {}
func (*EvalRequest_CheckedExpr) isEvalRequest_ExprKind() {}

func (m *EvalRequest) GetExprKind() isEvalRequest_ExprKind {
	if m != nil {
		return m.ExprKind
	}
	return nil
}

func (m *EvalRequest) GetParsedExpr() *syntax.ParsedExpr {
	if x, ok := m.GetExprKind().(*EvalRequest_ParsedExpr); ok {
		return x.ParsedExpr
	}
	return nil
}

func (m *EvalRequest) GetCheckedExpr() *checked.CheckedExpr {
	if x, ok := m.GetExprKind().(*EvalRequest_CheckedExpr); ok {
		return x.CheckedExpr
	}
	return nil
}

func (m *EvalRequest) GetBindings() map[string]*eval.ExprValue {
	if m != nil {
		return m.Bindings
	}
	return nil
}

func (m *EvalRequest) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*EvalRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _EvalRequest_OneofMarshaler, _EvalRequest_OneofUnmarshaler, _EvalRequest_OneofSizer, []interface{}{
		(*EvalRequest_ParsedExpr)(nil),
		(*EvalRequest_CheckedExpr)(nil),
	}
}

func _EvalRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*EvalRequest)
	// expr_kind
	switch x := m.ExprKind.(type) {
	case *EvalRequest_ParsedExpr:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ParsedExpr); err != nil {
			return err
		}
	case *EvalRequest_CheckedExpr:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CheckedExpr); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("EvalRequest.ExprKind has unexpected type %T", x)
	}
	return nil
}

func _EvalRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*EvalRequest)
	switch tag {
	case 1: // expr_kind.parsed_expr
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(syntax.ParsedExpr)
		err := b.DecodeMessage(msg)
		m.ExprKind = &EvalRequest_ParsedExpr{msg}
		return true, err
	case 2: // expr_kind.checked_expr
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(checked.CheckedExpr)
		err := b.DecodeMessage(msg)
		m.ExprKind = &EvalRequest_CheckedExpr{msg}
		return true, err
	default:
		return false, nil
	}
}

func _EvalRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*EvalRequest)
	// expr_kind
	switch x := m.ExprKind.(type) {
	case *EvalRequest_ParsedExpr:
		s := proto.Size(x.ParsedExpr)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EvalRequest_CheckedExpr:
		s := proto.Size(x.CheckedExpr)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type EvalResponse struct {
	Result               *eval.ExprValue `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Issues               []*rpc.Status   `protobuf:"bytes,2,rep,name=issues" json:"issues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *EvalResponse) Reset()         { *m = EvalResponse{} }
func (m *EvalResponse) String() string { return proto.CompactTextString(m) }
func (*EvalResponse) ProtoMessage()    {}
func (*EvalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cel_service_42f011481c95485e, []int{6}
}
func (m *EvalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvalResponse.Unmarshal(m, b)
}
func (m *EvalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvalResponse.Marshal(b, m, deterministic)
}
func (dst *EvalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvalResponse.Merge(dst, src)
}
func (m *EvalResponse) XXX_Size() int {
	return xxx_messageInfo_EvalResponse.Size(m)
}
func (m *EvalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EvalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EvalResponse proto.InternalMessageInfo

func (m *EvalResponse) GetResult() *eval.ExprValue {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *EvalResponse) GetIssues() []*rpc.Status {
	if m != nil {
		return m.Issues
	}
	return nil
}

func init() {
	proto.RegisterType((*StatusDetails)(nil), "google.api.expr.v1.StatusDetails")
	proto.RegisterType((*ParseRequest)(nil), "google.api.expr.v1.ParseRequest")
	proto.RegisterType((*ParseResponse)(nil), "google.api.expr.v1.ParseResponse")
	proto.RegisterType((*CheckRequest)(nil), "google.api.expr.v1.CheckRequest")
	proto.RegisterType((*CheckResponse)(nil), "google.api.expr.v1.CheckResponse")
	proto.RegisterType((*EvalRequest)(nil), "google.api.expr.v1.EvalRequest")
	proto.RegisterMapType((map[string]*eval.ExprValue)(nil), "google.api.expr.v1.EvalRequest.BindingsEntry")
	proto.RegisterType((*EvalResponse)(nil), "google.api.expr.v1.EvalResponse")
	proto.RegisterEnum("google.api.expr.v1.StatusDetails_Severity", StatusDetails_Severity_name, StatusDetails_Severity_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CelService service

type CelServiceClient interface {
	Parse(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error)
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	Eval(ctx context.Context, in *EvalRequest, opts ...grpc.CallOption) (*EvalResponse, error)
}

type celServiceClient struct {
	cc *grpc.ClientConn
}

func NewCelServiceClient(cc *grpc.ClientConn) CelServiceClient {
	return &celServiceClient{cc}
}

func (c *celServiceClient) Parse(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error) {
	out := new(ParseResponse)
	err := grpc.Invoke(ctx, "/google.api.expr.v1.CelService/Parse", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *celServiceClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	out := new(CheckResponse)
	err := grpc.Invoke(ctx, "/google.api.expr.v1.CelService/Check", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *celServiceClient) Eval(ctx context.Context, in *EvalRequest, opts ...grpc.CallOption) (*EvalResponse, error) {
	out := new(EvalResponse)
	err := grpc.Invoke(ctx, "/google.api.expr.v1.CelService/Eval", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CelService service

type CelServiceServer interface {
	Parse(context.Context, *ParseRequest) (*ParseResponse, error)
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	Eval(context.Context, *EvalRequest) (*EvalResponse, error)
}

func RegisterCelServiceServer(s *grpc.Server, srv CelServiceServer) {
	s.RegisterService(&_CelService_serviceDesc, srv)
}

func _CelService_Parse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CelServiceServer).Parse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.api.expr.v1.CelService/Parse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CelServiceServer).Parse(ctx, req.(*ParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CelService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CelServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.api.expr.v1.CelService/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CelServiceServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CelService_Eval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CelServiceServer).Eval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.api.expr.v1.CelService/Eval",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CelServiceServer).Eval(ctx, req.(*EvalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CelService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "google.api.expr.v1.CelService",
	HandlerType: (*CelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Parse",
			Handler:    _CelService_Parse_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _CelService_Check_Handler,
		},
		{
			MethodName: "Eval",
			Handler:    _CelService_Eval_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/cel-service.proto",
}

func init() {
	proto.RegisterFile("proto/v1/cel-service.proto", fileDescriptor_cel_service_42f011481c95485e)
}

var fileDescriptor_cel_service_42f011481c95485e = []byte{
	// 769 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcd, 0x4e, 0xf3, 0x46,
	0x14, 0xc5, 0xce, 0x0f, 0xc9, 0x75, 0x12, 0xa2, 0x69, 0x4b, 0xa3, 0x08, 0x68, 0x1a, 0xa9, 0x22,
	0x42, 0xc2, 0x11, 0x41, 0x95, 0xaa, 0x76, 0x51, 0x91, 0xc4, 0x94, 0x54, 0x21, 0x44, 0x13, 0x4a,
	0xd5, 0x6e, 0x2c, 0x33, 0x1e, 0x51, 0x0b, 0x33, 0x36, 0x1e, 0xc7, 0x4a, 0xa4, 0xee, 0xfb, 0x22,
	0x7d, 0x98, 0x3e, 0x47, 0x9f, 0xa0, 0x52, 0x37, 0x5d, 0x56, 0x9e, 0x99, 0x04, 0x02, 0x01, 0xc4,
	0xf7, 0xed, 0x6e, 0x8e, 0xcf, 0x3d, 0x73, 0xcf, 0xb9, 0x9e, 0x18, 0xea, 0x61, 0x14, 0xc4, 0x41,
	0x3b, 0x39, 0x6a, 0x13, 0xea, 0x1f, 0x72, 0x1a, 0x25, 0x1e, 0xa1, 0xa6, 0x00, 0x11, 0xba, 0x09,
	0x82, 0x1b, 0x9f, 0x9a, 0x4e, 0xe8, 0x99, 0x74, 0x16, 0x46, 0x66, 0x72, 0x54, 0xff, 0x5c, 0x62,
	0xed, 0x28, 0x24, 0x6d, 0x1e, 0x3b, 0xf1, 0x94, 0x4b, 0x72, 0x7d, 0x4f, 0x0a, 0x91, 0xdf, 0x28,
	0xb9, 0xa5, 0xae, 0x10, 0x94, 0xa5, 0x7a, 0xfe, 0xc9, 0xf2, 0x20, 0x9a, 0x38, 0xbe, 0x02, 0x3f,
	0x5b, 0x82, 0x7c, 0xce, 0x62, 0x67, 0x26, 0xe1, 0xe6, 0xdf, 0x1a, 0x94, 0x27, 0x42, 0xbc, 0x4f,
	0x63, 0xc7, 0xf3, 0x39, 0x3a, 0x85, 0x02, 0xa7, 0x09, 0x8d, 0xbc, 0x78, 0x5e, 0xd3, 0x1a, 0x5a,
	0xab, 0xd2, 0x39, 0x30, 0x9f, 0x4f, 0x67, 0xae, 0x34, 0x99, 0x13, 0xd5, 0x81, 0x97, 0xbd, 0x08,
	0x41, 0xd6, 0xf7, 0x18, 0xad, 0xe9, 0x0d, 0xad, 0x95, 0xc3, 0xa2, 0x46, 0xdb, 0x90, 0x27, 0x81,
	0x3f, 0xbd, 0x63, 0xb5, 0x8c, 0x40, 0xd5, 0x2f, 0x54, 0x01, 0xdd, 0x73, 0x6b, 0xd9, 0x86, 0xd6,
	0xca, 0x60, 0xdd, 0x73, 0x9b, 0xe7, 0x50, 0x58, 0x28, 0xa2, 0x1a, 0x7c, 0x3a, 0xb1, 0xae, 0x2c,
	0x3c, 0xb8, 0xfc, 0xc5, 0xfe, 0x69, 0x34, 0x19, 0x5b, 0xbd, 0xc1, 0xe9, 0xc0, 0xea, 0x57, 0x37,
	0xd0, 0x16, 0x18, 0x7d, 0x6b, 0x8c, 0xad, 0xde, 0xc9, 0xe5, 0xe0, 0x62, 0x54, 0xd5, 0x90, 0x01,
	0x9b, 0x3f, 0x9f, 0xe0, 0xd1, 0x60, 0xf4, 0x43, 0x55, 0x47, 0x45, 0xc8, 0x59, 0x18, 0x5f, 0xe0,
	0x6a, 0xa6, 0xf9, 0xa7, 0x06, 0xa5, 0xb1, 0x13, 0x71, 0x8a, 0xe9, 0xfd, 0x94, 0xf2, 0x18, 0xed,
	0x02, 0x10, 0xea, 0xdb, 0x3c, 0x98, 0x46, 0x84, 0x0a, 0x97, 0x45, 0x5c, 0x24, 0xd4, 0x9f, 0x08,
	0x00, 0x7d, 0x05, 0x15, 0x19, 0x92, 0x9d, 0xd0, 0x88, 0x7b, 0x01, 0x13, 0x26, 0x8a, 0xb8, 0x2c,
	0xd1, 0x2b, 0x09, 0xa2, 0x7d, 0xd8, 0x92, 0x0a, 0xb6, 0x1f, 0x10, 0x27, 0x4e, 0x79, 0x19, 0xc1,
	0xab, 0x48, 0x78, 0xa8, 0xd0, 0x54, 0xcf, 0xf5, 0xb8, 0x73, 0xed, 0x53, 0xfb, 0xce, 0x21, 0x51,
	0xc0, 0x85, 0xd5, 0x02, 0x2e, 0x2b, 0xf4, 0x5c, 0x80, 0xcd, 0xdf, 0xa1, 0xac, 0xa6, 0xe4, 0x61,
	0xc0, 0x38, 0x45, 0xdf, 0x83, 0x11, 0xa6, 0x80, 0x6b, 0xa7, 0xa9, 0x8b, 0x39, 0x8d, 0xce, 0xde,
	0xba, 0x6d, 0x88, 0x3e, 0xd7, 0x9a, 0x85, 0x11, 0x86, 0x70, 0x59, 0xa3, 0x03, 0xc8, 0x7b, 0x9c,
	0x4f, 0x29, 0xaf, 0xe9, 0x8d, 0x4c, 0xcb, 0xe8, 0xa0, 0x45, 0x6f, 0x14, 0x12, 0xb5, 0x41, 0xac,
	0x18, 0xcd, 0xbf, 0x34, 0x28, 0xf5, 0xd2, 0xf7, 0x68, 0x11, 0xd2, 0x47, 0x9f, 0xfe, 0x1d, 0x14,
	0xe2, 0x79, 0x48, 0x6d, 0xca, 0x12, 0x75, 0x7e, 0xe3, 0x59, 0xf7, 0xe2, 0xcd, 0x4d, 0x8e, 0xcc,
	0x3e, 0x25, 0x3e, 0xde, 0x4c, 0x3b, 0x2c, 0x96, 0xa0, 0x1d, 0x28, 0x92, 0x80, 0xc5, 0x8e, 0xc7,
	0x68, 0xa4, 0x62, 0x7d, 0x00, 0xd0, 0x0e, 0x00, 0x0b, 0x6c, 0x1e, 0xbb, 0x42, 0x5c, 0xa6, 0x59,
	0x60, 0xc1, 0x24, 0x76, 0x2d, 0x96, 0x34, 0xff, 0xd0, 0xa0, 0xac, 0xac, 0xa8, 0x24, 0x7f, 0x84,
	0x92, 0x3a, 0xe9, 0xb1, 0x99, 0xfd, 0xd7, 0xc6, 0xe9, 0xc9, 0x52, 0xb8, 0x32, 0xc8, 0xc3, 0x8f,
	0x77, 0x85, 0xfa, 0x8f, 0x0e, 0x86, 0x95, 0x38, 0xfe, 0x22, 0xd3, 0x93, 0x0f, 0xc8, 0xf4, 0x6c,
	0x63, 0x25, 0xd5, 0xe1, 0x13, 0x2b, 0xfa, 0xbb, 0xac, 0x9c, 0x6d, 0xac, 0x9a, 0x19, 0x40, 0xe1,
	0xda, 0x63, 0xae, 0xc7, 0x6e, 0x78, 0x2d, 0x23, 0xec, 0x1c, 0xae, 0x9b, 0xe6, 0x91, 0x07, 0xb3,
	0xab, 0xf8, 0x16, 0x8b, 0xa3, 0x39, 0x5e, 0xb6, 0xaf, 0x6e, 0x2c, 0xfb, 0x64, 0x63, 0xf5, 0x5f,
	0xa1, 0xbc, 0xd2, 0x88, 0xaa, 0x90, 0xb9, 0xa5, 0x73, 0x75, 0xf9, 0xd2, 0x12, 0x1d, 0x43, 0x2e,
	0x71, 0xfc, 0x29, 0x55, 0x96, 0x76, 0xd7, 0x0e, 0x32, 0x0b, 0xa3, 0xab, 0x94, 0x84, 0x25, 0xf7,
	0x5b, 0xfd, 0x1b, 0xad, 0x6b, 0x40, 0x31, 0x7d, 0x6e, 0xdf, 0x7a, 0xcc, 0x6d, 0xde, 0x43, 0x49,
	0x4e, 0xab, 0x56, 0xff, 0x35, 0xe4, 0x23, 0xca, 0xa7, 0x7e, 0xac, 0xd2, 0x7e, 0x43, 0x56, 0x91,
	0xdf, 0xb3, 0xe5, 0xce, 0xbf, 0x1a, 0x40, 0x8f, 0xfa, 0x13, 0xf9, 0x97, 0x8e, 0x86, 0x90, 0x13,
	0xdb, 0x43, 0x8d, 0x17, 0x17, 0xab, 0xb2, 0xac, 0x7f, 0xf9, 0x0a, 0x43, 0xcd, 0x3f, 0x84, 0x9c,
	0xd8, 0xdf, 0x7a, 0xb5, 0xc7, 0x37, 0x76, 0xbd, 0xda, 0xea, 0x45, 0x18, 0x40, 0x36, 0x4d, 0x07,
	0x7d, 0xf1, 0xc6, 0x96, 0xeb, 0x8d, 0x97, 0x09, 0x52, 0xaa, 0x6b, 0xc2, 0x36, 0x09, 0xee, 0xd6,
	0xd0, 0xba, 0x5b, 0x0f, 0x61, 0x8c, 0xd3, 0xaf, 0xcc, 0x58, 0xfb, 0x4f, 0xd3, 0xae, 0xf3, 0xe2,
	0x8b, 0x73, 0xfc, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x72, 0x46, 0x2a, 0x0f, 0x08, 0x07, 0x00,
	0x00,
}
